start transaction;
drop table if exists Catalogs;

create table Catalogs
(
	designator		varchar(32) not null,
	name			varchar(64) not null,
	catalog_type	varchar(64) not null,
	primary key ( designator )
);

insert into Catalogs values
( '3C', 'Third Cambridge Catalog of Radio Wave Sources', 'radio sources' ),
( 'Abell', 'George Abell', 'planetary nebulae and galaxy clusters' ),
( 'ADS', 'Aitken Double Star catalog', 'double stars' ),
( 'AM', 'Arp-Madore', 'globular clusters' ),
( 'Antalova', 'Antalova', 'open clusters' ),
( 'Ap', 'Apriamasvili', 'planetary nebulae' ),
( 'Arp', 'Halton Arp', 'interacting galaxies' ),
( 'A', 'Aitken, R.G.', 'multiple stars' ),
( 'AC', 'Clark, Alvan', 'multiple stars' ),
( 'AG', 'AG catalog', 'multiple stars' ),
( 'ARG', 'Argelander, F.', 'multiple stars' ),
( 'Bark', 'Barkhatova', 'open clusters' ),
( 'B', 'Barnard', 'dark nebulae' ),
( 'Basel', 'Basel', 'open clusters' ),
( 'BD', 'Bonner Durchmusterung', 'stars' ),
( 'Berk', 'Berkeley', 'open clusters' ),
( 'Be', 'Bernes', 'dark nebulae' ),
( 'Biur', 'Biurakan', 'open clusters' ),
( 'Blanco', 'Blanco', 'open clusters' ),
( 'Bochum', 'Bochum', 'open clusters' ),
( 'Bos', 'Bos, W.H. van den', 'multiple stars' ),
( 'BrsO', 'Brisbane Obs.', 'multiple stars' ),
( 'BUP', 'Burnham, S.W. pm', 'multiple stars' ),
( 'Ced', 'Cederblad', 'bright nebulae' ),
( 'CCCS', 'Catalog of Cool Carbon Stars', 'carbon stars' ),
( 'CD', 'Cape Durchmusterung', 'stars' ),
( 'CGCG', 'Catalog of Galaxies and Clusters of Galaxies', 'galaxies' ),
( 'Cr', 'Collinder', 'open clusters' ),
( 'Czernik', 'Czernik', 'open clusters' ),
( 'COO', 'Cordoba Obs.', 'multiple stars' ),
( 'COU', 'Couteau, P.', 'multiple stars' ),
( 'CPO', 'Cape Observatory', 'multiple stars' ),
( 'DDO', 'David Dunlap Observatory', 'dwarf galaxies' ),
( 'Do', 'Dolidze', 'open clusters' ),
( 'DoDz', 'Dolidze-Dzimselejsvili', 'open clusters' ),
( 'Dun', 'Dunlop', 'Southern objects of all types' ),
( 'DON', 'Donner, H.F.', 'multiple stars' ),
( 'ESO', 'European Southern Observatory', 'Southern objects' ),
( 'ES', 'Espin, T.E.', 'multiple stars' ),
( 'Fein', 'Feinstein', 'open clusters' ),
( 'Frolov', 'Frolov', 'open clusters' ),
( 'Gum', 'Gum', 'bright nebulae' ),
( 'GLI', 'Gilliss, J.M.', 'multiple stars' ),
( 'GRB', 'Groombridge, S.', 'multiple stars' ),
( 'H I', 'William Herschel', 'all types of objects' ),
( 'H II', 'William Herschel', 'all types of objects' ),
( 'H III', 'William Herschel', 'all types of objects' ),
( 'H IV', 'William Herschel', 'all types of objects' ),
( 'H V', 'William Herschel', 'all types of objects' ),
( 'H VI', 'William Herschel', 'all types of objects' ),
( 'H VII', 'William Herschel', 'all types of objects' ),
( 'H VIII', 'William Herschel', 'all types of objects' ),
( 'Haffner', 'Haffner', 'open clusters' ),
( 'Harvard', 'Harvard', 'open clusters' ),
( 'Hav-Moffat', 'Havermeyer and Moffat', 'open clusters' ),
( 'HD', 'Henry Draper', 'stars' ),
( 'He', 'Henize', 'planetary nebulae' ),
( 'Hogg', 'Hogg', 'open clusters' ),
( 'Ho', 'Holmberg', 'galaxies' ),
( 'HP', 'Haute Provence', 'globular clusters' ),
( 'Hu', 'Humason', 'planetary nebulae' ),
( 'HDO', 'Harvard Obs.', 'multiple stars' ),
( 'HEI', 'Heintz, W.D.', 'multiple stars' ),
( 'h', 'Herschel, J.', 'multiple stars' ),
( 'HRG', 'Hargrave, L.', 'multiple stars' ),
( 'HU', 'Hussey, W.L.', 'multiple stars' ),
( 'IC', '1st and 2nd Index Catalogs to the NGC', 'all types of objects except dark nebulae' ),
( 'Isk', 'Iskudarian', 'open clusters' ),
( 'I', 'Innes, R.T.A.', 'multiple stars' ),
( 'J', 'Jonckheere, R', 'various types of objects' ),
( 'JC', 'Jacob, W.S.', 'multiple stars' ),
( 'K', 'Kohoutek', 'planetary nebulae' ),
( 'Kemble', 'Father Lucian Kemble', 'asterisms' ),
( 'King', 'King', 'open clusters' ),
( 'Kra', 'Krasnogorskaja', 'planetary nebulae' ),
( 'Kr', 'Kruger, A', 'multiple stars' ),
( 'Lac', 'Lacaille', 'globular clusters' ),
( 'Loden', 'Loden', 'open clusters' ),
( 'LBN', 'Lynds', 'bright nebula' ),
( 'LDN', 'Lynds', 'dark nebulae' ),
( 'Lynga', 'Lynga', 'open clusters' ),
( 'L', 'Lewis, T.', 'multiple stars' ),
( 'LAL', 'Lalande, F. de', 'multiple stars' ),
( 'MLB', 'Milburn, W.', 'multiple stars' ),
( 'MLO', 'Melbourne Obs.', 'multiple stars' ),
( 'M', 'Messier', 'all types of objects except dark nebula' ),
( 'MCG', 'Morphological Catalog of Galaxies', 'galaxies' ),
( 'Me', 'Merrill', 'plantary nebulae' ),
( 'Mrk', 'Markarian', 'open clusters and galaxies' ),
( 'Mel', 'Melotte', 'open clusters' ),
( 'M1', 'Minkowski', 'planetary nebulae' ),
( 'M2', 'Minkowski', 'planetary nebulae' ),
( 'M3', 'Minkowski', 'planetary nebulae' ),
( 'M4', 'Minkowski', 'planetary nebulae' ),
( 'New', 'New galaxies in the Revised Shapley-Ames Catalog', 'galaxies' ),
( 'NGC', 'New General Catalog of Nebulae & Clusters of Stars', 'all types of objects except dark nebulae' ),
( 'NPM1G', 'Northern Proper Motion 1st part Galaxies', 'galaxies' ),
( 'Pal', 'Palomar', 'globular clusters' ),
( 'PB', 'Peimbert and Batiz', 'planetary nebulae' ),
( 'PC', 'Peimbert and Costero', 'planetary nebulae' ),
( 'Pismis', 'Pismis', 'open clusters' ),
( 'PK', 'Perek & Kohoutek', 'planetary nebulae' ),
( 'PZ', 'Piazzi, G.', 'multiple stars' ),
( 'RCW', 'Rodgers Campbell & Whiteoak', 'bright nebulae' ),
( 'Roslund', 'Roslund', 'open clusters' ),
( 'Ru', 'Ruprecht', 'open clusters' ),
( 'R', 'Russell, H.C.', 'multiple stars' ),
( 'SAO', 'Smithsonian Astrophysical Observatory Catalog', 'stars' ),
( 'RMK', 'Rumker, C.', 'multiple stars' ),
( 'Sa', 'Sandqvist', 'dark nebulae' ),
( 'Sher', 'Sher', 'open clusters' ),
( 'Sh', 'Sharpless', 'bright nebulae' ),
( 'SL', 'Sandqvist & Lindroos', 'dark nebulae' ),
( 'ShL', 'Shapley & Lindsay', 'clusters in LMC' ),
( 'Steph', 'Stephenson', 'open clusters' ),
( 'Stock', 'Stock', 'open clusters' ),
( 'SEE', 'See, T.J.', 'multiple stars' ),
( 'SEI', 'Scheiner, J.', 'multiple stars' ),
( 'SH', 'South & Herschel', 'multiple stars' ),
( 'SLR', 'Sellors, R.P.', 'multiple stars' ),
( 'STF ', 'Struve, F.G.W.', 'multiple stars' ),
( 'STT', 'Struve, Otto', 'multiple stars' ),
( 'Ter', 'Terzan', 'globular clusters' ),
( 'Tombaugh', 'Tombaugh', 'open clusters' ),
( 'Ton', 'Tonantzintla', 'globular clusters' ),
( 'Tr', 'Trumpler', 'open clusters' ),
( 'TYC', 'Tycho Catalog', 'stars' ),
( 'UGC', 'Uppsala General Catalog', 'galaxies' ),
( 'UGCA', 'Uppsala General Catalog Addendum', 'galaxies' ),
( 'UKS', 'United Kingdom Schmidt', 'globular clusters' ),
( 'Upgren', 'Upgren', 'open clusters' ),
( 'V V', 'Vorontsov-Velyaminov', 'interacting galaxies' ),
( 'vdB', 'van den Bergh', 'open clusters & bright nebulae' ),
( 'vdBH', 'van den Bergh & Herbst', 'bright nebulae' ),
( 'vdB-Ha', 'van den Bergh-Hagen', 'open clusters' ),
( 'Vy', 'Vyssotsky', 'planetary nebulae' ),
( 'Waterloo', 'Waterloo', 'open clusters' ),
( 'Winnecke', 'Double Star', 'Messier 40' ),
( 'ZwG', 'Zwicky', 'galaxies' ),
( 'WEI', 'Weisse, M.', 'multiple stars' ),
( 'WNC', 'Winnecke, A.', 'multiple stars' );