start transaction;
drop table if exists Constellations;
create table Constellations
(
	abbreviationIAU			char(3) not null,
	abbreviationSAC			char(3) not null,
	abbreviationNASA		char(4) not null,
	name					varchar(64) not null,
	primary key ( abbreviationIAU ),
	unique key ( abbreviationSAC ),
	unique key ( abbreviationNASA ),
	unique key ( name )
);

insert into Constellations values
( 'And', 'AND', 'Andr', 'Andromeda' ),
( 'Ant', 'ANT', 'Antl', 'Antlia' ),
( 'Aps', 'APS', 'Apus', 'Apus' ),
( 'Aqr', 'AQR', 'Aqar', 'Aquarius' ),
( 'Aql', 'AQL', 'Aqil', 'Aquila' ),
( 'Ara', 'ARA', 'Arae', 'Ara' ),
( 'Ari', 'ARI', 'Arie', 'Aries' ),
( 'Aur', 'AUR', 'Auri', 'Auriga' ),
( 'Boo', 'BOO', 'Boot', 'Bootes' ),
( 'Cae', 'CAE', 'Cael', 'Caelum' ),
( 'Cam', 'CAM', 'Caml', 'Camelopardalis' ),
( 'Cnc', 'CNC', 'Canc', 'Cancer' ),
( 'CVn', 'CVN', 'CVen', 'Canes Venatici' ),
( 'CMa', 'CMA', 'CMaj', 'Canis Major' ),
( 'CMi', 'CMI', 'CMin', 'Canis Minor' ),
( 'Cap', 'CAP', 'Capr', 'Capricornus' ),
( 'Car', 'CAR', 'Cari', 'Carina' ),
( 'Cas', 'CAS', 'Cass', 'Cassiopeia' ),
( 'Cen', 'CEN', 'Cent', 'Centaurus' ),
( 'Cep', 'CEP', 'Ceph', 'Cepheus' ),
( 'Cet', 'CET', 'Ceti', 'Cetus' ),
( 'Cha', 'CHA', 'Cham', 'Chamaeleon' ),
( 'Cir', 'CIR', 'Circ', 'Circinus' ),
( 'Col', 'COL', 'Colm', 'Columba' ),
( 'Com', 'COM', 'Coma', 'Coma Berenices' ),
( 'CrA', 'CRA', 'CorA', 'Corona Australis' ),
( 'CrB', 'CRB', 'CorB', 'Corona Borealis' ),
( 'Crv', 'CRV', 'Corv', 'Corvus' ),
( 'Crt', 'CRT', 'Crat', 'Crater' ),
( 'Cru', 'CRU', 'Cruc', 'Crux' ),
( 'Cyg', 'CYG', 'Cygn', 'Cygnus' ),
( 'Del', 'DEL', 'Dlph', 'Delphinus' ),
( 'Dor', 'DOR', 'Dora', 'Dorado' ),
( 'Dra', 'DRA', 'Drac', 'Draco' ),
( 'Equ', 'EQU', 'Equl', 'Equuleus' ),
( 'Eri', 'ERI', 'Erid', 'Eridanus' ),
( 'For', 'FOR', 'Forn', 'Fornax' ),
( 'Gem', 'GEM', 'Gemi', 'Gemini' ),
( 'Gru', 'GRU', 'Grus', 'Grus' ),
( 'Her', 'HER', 'Herc', 'Hercules' ),
( 'Hor', 'HOR', 'Horo', 'Horologium' ),
( 'Hya', 'HYA', 'Hyda', 'Hydra' ),
( 'Hyi', 'HYI', 'Hydi', 'Hydrus' ),
( 'Ind', 'IND', 'Indi', 'Indus' ),
( 'Lac', 'LAC', 'Lacr', 'Lacerta' ),
( 'Leo', 'LEO', 'Leon', 'Leo' ),
( 'LMi', 'LMI', 'LMin', 'Leo Minor' ),
( 'Lep', 'LEP', 'Leps', 'Lepus' ),
( 'Lib', 'LIB', 'Libr', 'Libra' ),
( 'Lup', 'LUP', 'Lupi', 'Lupus' ),
( 'Lyn', 'LYN', 'Lync', 'Lynx' ),
( 'Lyr', 'LYR', 'Lyra', 'Lyra' ),
( 'Men', 'MEN', 'Mens', 'Mensa' ),
( 'Mic', 'MIC', 'Micr', 'Microscopium' ),
( 'Mon', 'MON', 'Mono', 'Monoceros' ),
( 'Mus', 'MUS', 'Musc', 'Musca' ),
( 'Nor', 'NOR', 'Norm', 'Norma' ),
( 'Oct', 'OCT', 'Octn', 'Octans' ),
( 'Oph', 'OPH', 'Ophi', 'Ophiuchus' ),
( 'Ori', 'ORI', 'Orio', 'Orion' ),
( 'Pav', 'PAV', 'Pavo', 'Pavo' ),
( 'Peg', 'PEG', 'Pegs', 'Pegasus' ),
( 'Per', 'PER', 'Pers', 'Perseus' ),
( 'Phe', 'PHE', 'Phoe', 'Phoenix' ),
( 'Pic', 'PIC', 'Pict', 'Pictor' ),
( 'Psc', 'PSC', 'Pisc', 'Pisces' ),
( 'PsA', 'PSA', 'PscA', 'Pisces Austrinus' ),
( 'Pup', 'PUP', 'Pupp', 'Puppis' ),
( 'Pyx', 'PYX', 'Pyxi', 'Pyxis' ),
( 'Ret', 'RET', 'Reti', 'Reticulum' ),
( 'Sge', 'SGE', 'Sgte', 'Sagitta' ),
( 'Sgr', 'SGR', 'Sgtr', 'Sagittarius' ),
( 'Sco', 'SCO', 'Scor', 'Scorpius' ),
( 'Scl', 'SCL', 'Scul', 'Sculptor' ),
( 'Sct', 'SCT', 'Scut', 'Scutum' ),
( 'Ser', 'SER', 'Serp', 'Serpens' ),
( 'Sex', 'SEX', 'Sext', 'Sextans' ),
( 'Tau', 'TAU', 'Taur', 'Taurus' ),
( 'Tel', 'TEL', 'Tele', 'Telescopium' ),
( 'TrA', 'TRA', 'TrAu', 'Triangulum Australe' ),
( 'Tri', 'TRI', 'Tria', 'Triangulum' ),
( 'Tuc', 'TUC', 'Tucn', 'Tucana' ),
( 'UMa', 'UMA', 'UMaj', 'Ursa Major' ),
( 'UMi', 'UMI', 'UMin', 'Ursa Minor' ),
( 'Vel', 'VEL', 'Velr', 'Vela' ),
( 'Vir', 'VIR', 'Virg', 'Virgo' ),
( 'Vol', 'VOL', 'Voln', 'Volans' ),
( 'Vul', 'VUL', 'Vulp', 'Vulpecula' );

commit;
